######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 17 21:35:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calc.h
FORMS += calc.ui
SOURCES += calc.cpp main.cpp
