######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 17 21:35:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calculator.h \
           dialog.h
FORMS += calculator.ui \
          dialog.ui
SOURCES += calculator.cpp main.cpp dialog.cpp
